### ISSUE TITLE
Handling width of constants

### ISSUE THREAD

**Issue by sushant94** [radare/radeco-lib#79]
Current implementation of SSA construction sets constants to be 64-bit wide by default. This leads to every use of the constant widening the other operations.

**Comment by sushant94** [comment]
@ZhangZhuoSJTU Some thoughts
-  Since we try our best to maintain exactly one copy of a constant (across multiple uses), how do we want to assign the with to the Constant node. The same constant maybe used several times with different widths.

Example:
```
mov eax, 64;
.....
mov rbx, 64;
``` 
We need a way to handle this, or we simply need to create another constant node with a different size.
Three options I can think of:
 - Set constants to have an `adaptive` size that takes the size of whatever the other operand is. But this will need special handling to check the other operand's size in our analysis etc., which in my opinion is not ergonomic.
- Duplicate constants and set size whenever an existing one is not compatible.
- Always have defined constants to be 64-bit wide, but narrow them (if needed) before use, instead of widening the other operand.

**Comment by ZhangZhuoSJTU** [comment]
@sushant94 To be honest, for me maintaining exactly one copy of a constant is the best idea. And before talking about which options we choose, one point should be concerned:

**In some analysis, especially like `sccp`, we haven't maintain exactly one copy of a constant, which actually needs some improvement.**

In my opinion, the third one is much better, because in this way, we could avoid widening on some uncertain operands and distinguishing signed v/s zero widening. Some patches I have added are following this method, but I'm not sure I covered all the situation.

**Comment by sushant94** [comment]
Ok, that's cool! I'm going to test it out and see how it works for different cases. If it works out fine, we can just close this issue.

**Comment by ZhangZhuoSJTU** [comment]
As for #92 , I think this issue could be closed. @sushant94

**Comment by sushant94** [comment]
Done in #92
