### ISSUE TITLE
Standardize the SSA API

### ISSUE THREAD

**Issue by sushant94** [radare/radeco-lib#80]
Most functions in the SSA/SSAMod/CFG/CFGMod API follow a certain pattern in naming and arguments. It would be nice to standardize it and have all functions be uniform, making the naming and usage more consistent and predictable.

**Comment by ZhangZhuoSJTU** [comment]
I am a little confused about this issue. Emm, do you mean the SSA API is a little mess? Like `args_of` and `get_operands` functions work on the same things?

**Comment by sushant94** [comment]
Yes, that's what I mean. We should streamline it and decide what actually stays and what an be removed (also, what could be added).

**Comment by ZhangZhuoSJTU** [comment]
I see. I will make an API list later for more specific discussion.

**Comment by ZhangZhuoSJTU** [comment]
@sushant94  @XVilka @chinmaydd  Need some suggestions about new API.

# SSA API

## Naming Convention

- `action` is used to describe basic blocks.

- `value` is used to describe SSA node (Const, Expr, Phi).

- `edge` is used to describe CFG edges. (Except basic functions, edges are used to describe all edges)

## Struct Define

```rust
pub struct SSAStorage {
    pub g: StableDiGraph<NodeData, EdgeData>,
    pub start_node: NodeIndex,
    pub exit_node: NodeIndex,
    pub assoc_data: AssociatedData,
    pub regnames: Vec<String>,
    pub constants: HashMap<u64, NodeIndex>,
}
```

## Basic Functions

- default::Default

    - fn default() -> SSAStorage;

- impl SSAStorage 

    - pub fn new() -> SSAStorage

    - pub fn nodes(&self) -> Vec<NodeIndex> 

    - pub fn node\_count(&self) -> usize 

    - pub fn edge\_count(&self) -> usize 

    - fn insert\_node(&mut self, d: NodeData) -> NodeIndex

    - fn remove\_node(&mut self, exi: NodeIndex)

    - fn replace\_node(&mut self, i: NodeIndex, j: NodeIndex)

    - fn insert\_edge(&mut self, i: NodeIndex, j: NodeIndex, e: EdgeData) -> EdgeIndex 

    - fn update\_edge(&mut self, i: NodeIndex, j: NodeIndex, e: EdgeData) -> EdgeIndex 

    - fn delete\_edge(&mut self, i: NodeIndex, j: NodeIndex) 

    - fn find\_edge(&self, source: &NodeIndex, target: &NodeIndex) -> Vec<EdgeIndex> 

    - fn edge\_info(&self, i: &EdgeIndex) -> (NodeIndex, NodeIndex) 

    - fn gather\_adjacent(&self, node: NodeIndex, direction: EdgeDirection, data: bool) -> Vec<NodeIndex>


## CFG

```rust
type ActionRef = NodeIndex;
type CFEdgeRef = EdgeIndex;
```

- fn is\_block(&self, node: &Self::ActionRef) -> bool 

- fn is\_action(&self, action: &Self::ActionRef) -> bool 

- fn blocks(&self) -> Vec<Self::ActionRef> 

- fn start\_node(&self) -> Self::ActionRef 

- fn exit\_node(&self) -> Self::ActionRef 

- fn preds\_of(&self, exi: &Self::ActionRef) -> Vec<Self::ActionRef> 

- fn succs\_of(&self, exi: &Self::ActionRef) -> Vec<Self::ActionRef> 

- fn true\_edge\_of(&self, i: &Self::ActionRef) -> Self::CFEdgeRef 

- fn false\_edge\_of(&self, i: &Self::ActionRef) -> Self::CFEdgeRef 

- fn next\_edge\_of(&self, i: &Self::ActionRef) -> Self::CFEdgeRef 

- fn incoming\_edges(&self, i: &Self::ActionRef) -> Vec<(Self::CFEdgeRef, u8)> 

- fn outgoing\_edges(&self, i: &Self::ActionRef) -> Vec<(Self::CFEdgeRef, u8)> 

- fn get\_next\_block(&self, i: &Self::ActionRef) -> Self::ActionRef 

- fn get\_conditional\_blocks(&self, i: &Self::ActionRef) -> (Self::ActionRef, Self::ActionRef) 

- fn address(&self, si: &Self::ActionRef) -> Option<MAddress> 

- fn invalid\_edge(&self) -> Self::CFEdgeRef 

- fn invalid\_action(&self) -> Self::ActionRef 

## CFGMod

```rust
type BBInfo = MAddress;
```

- fn set\_start\_node(&mut self, si: Self::ActionRef) 

- fn set\_exit\_node(&mut self, ei: Self::ActionRef)

- fn add\_block(&mut self, info: Self::BBInfo) -> Self::ActionRef

- fn add\_dynamic(&mut self) -> Self::ActionRef

- fn add\_control\_edge(&mut self, source: Self::ActionRef, target: Self::ActionRef, index: u8) 

- fn remove\_block(&mut self, exi: Self::ActionRef) 

- fn remove\_control\_edge(&mut self, edge: Self::CFEdgeRef)


## SSA 

```rust
type ValueRef = NodeIndex;
```

- fn get\_address(&self, ni: &Self::ValueRef) -> MAddress 

- fn exprs\_in(&self, i: &Self::ValueRef) -> Vec<Self::ValueRef> 

- fn phis\_in(&self, exi: &Self::ValueRef) -> Vec<Self::ValueRef>

- fn registers\_in(&self, exi: &Self::ValueRef) -> Self::ValueRef 

- fn is\_selector(&self, exi: &Self::ValueRef) -> bool 

- fn is\_expr(&self, exi: &Self::ValueRef) -> bool

- fn is\_phi(&self, exi: &Self::ValueRef) -> bool 

- fn selects\_for(&self, i: &Self::ValueRef) -> Self::ActionRef

- fn selector\_of(&self, i: &Self::ActionRef) -> Self::ValueRef

- fn get\_uses(&self, i: &Self::ValueRef) -> Vec<Self::ValueRef>

- fn get\_register(&self, i: &Self::ValueRef) -> Vec<String>

- fn get\_block(&self, i: &Self::ValueRef) -> Self::ValueRef

- fn get\_selector\_branches(&self, exi: &Self::ValueRef) -> (Self::ValueRef, Self::ValueRef)

- fn get\_operands(&self, exi: &Self::ValueRef) -> Vec<Self::ValueRef>

- fn get\_sparse\_operands(&self, exi: &Self::ValueRef) -> Vec<(u8, Self::ValueRef)> 

- fn get\_node\_data(&self, i: &Self::ValueRef) -> Result<TNodeData, Box<Debug>>

- fn get\_const(&self, ni: &Self::ValueRef) -> Option<u64> 

- fn get\_comment(&self, i: &Self::ValueRef) -> Option<String> 

- fn get\_opcode(&self, i: &Self::ValueRef) -> Option<MOpcode>

- fn get\_uses(&self, node: &Self::ValueRef) -> Vec<Self::ValueRef> 

- fn invalid\_value(&self) -> Self::ValueRef 


## SSAMod

- fn set\_addr(&mut self, i: Self::ValueRef, addr: MAddress) 

- fn set\_register(&mut self, i: Self::ValueRef, regname: &String) 

- fn set\_selector(&mut self, node: Self::ValueRef, block: Self::ActionRef) 

- fn add\_op(&mut self, vt: ValueInfo, opc: MOpcode) -> Self::ValueRef 

- fn add\_const(&mut self, value: u64) -> Self::ValueRef 

- fn add\_phi(&mut self, vt: ValueInfo) -> Self::ValueRef 

- fn add\_undefined(&mut self, vt: ValueInfo) -> Self::ValueRef 

- fn add\_comment(&mut self, vt: ValueInfo, msg: String) -> Self::ValueRef 

- fn phi\_use(&mut self, phi: Self::ValueRef, node: Self::ValueRef) 

- fn phi\_unuse(&mut self, phi: Self::ValueRef, node: Self::ValueRef)

- fn op\_use(&mut self, node: Self::ValueRef, index: u8, argument: Self::ValueRef) 

- fn op\_unuse(&mut self, op: Self::ValueRef, operand: Self::ValueRef) 

- fn replace\_value(&mut self, node: Self::ValueRef, replacement: Self::ValueRef) 

- fn remove\_value(&mut self, node: Self::ValueRef)

- fn add\_to\_block(&mut self, node: Self::ValueRef, block: Self::ActionRef, at: MAddress) 

- fn map\_registers(&mut self, regs: Vec<String>)

**Comment by ZhangZhuoSJTU** [comment]
Sorry about forgetting highlight. I will highlight the list later.

**Comment by ZhangZhuoSJTU** [comment]
@sushant94  @XVilka @chinmaydd Updata list ;P

**Comment by chinmaydd** [comment]
Looks great izhuer :)

Some suggestions (in no particular order, sorry about that):

#### High-level:
* Choose one between `remove` and `delete`?
* Maybe follow a convention for getter and setters: `insert/update/remove/replace`. Also `get_xx` and `set_xx`. It might make API functions a bit longer but I think that design is better.
* Some functions are taking references to NodeIndex/EdgeIndex while some are not. Maybe we need to update those properly to follow a set standard.

#### SSAStorage:
* In `arch-rs` we are planning to reference registers using a certain index into the RegisterFile. If we are using the same concept here, we can save those indices instead of `pub regnames: Vec<String>,` in SSAStorage. This might require some code changes for getting register names but then we can query for them as required. Also saves space ;)
* Maybe return `EdgeData` and `EdgeDirection` in `edge_info()` in SSAStorage and place it into a nice structure(marking source and index nodes) rather than use a tuple?
* Adding a `node_info()` method would be helpful as well I think. 
* Very likely a typing mistake, but why are most functions private?

#### CFG
* Maybe rename the function `is_action()`? Not sure about this, but give it a more verbose name.
* Having a Error enum for Radeco CFG is necessary I think. 
* For `true_edge_of()` and `false_edge_of` I think we should return an Result<> containing a `RadecoError` so that if those are called on blocks with no conditional branches, it informs the user about it.
* Applying above suggestion to other functions in the trait as well. (`get_conditional_blocks`, `get_next_block`, etc.
* I think we should avoid using tuples. It will introduce coding pattern like: `result.1`. For someone new to reading code it will portray a wrong picture. Instead maybe have a struct with `result.true` and `result.false` for accessing results. I agree it may increase redundant code but maybe we can use something existing for this.

I will update this comment tomorrow.

**Comment by ZhangZhuoSJTU** [comment]
@chinmaydd Hah, thanks for your suggestions. That does help a lot.

+ For **High-level**    I will do some changes right now ;P
+ For **SSAStorage**
    + `ragname` is considered to change for `arch-rs`
    +  For `edge_info` and `node_info`, I am not sure if it's necessary, because we could access these information from higher APIs, like `get_node_data`. I leave the  `edge_info` to be discussed because the original code has this function but never use anywhere.
    + For private functions, hah, that's because CFG/CFGMod/SSA/SSAMod all are traits, in implement I ignore the `pub` key word ;D
+ For **CFG**
    + `action` includes all the basic blocks and the special exit node.
    + For `true_edge_of()` and similar function, nice catch. That's what I need suggestions most. Actually these functions will return an invalid edge/action/value if no exist (`EdgeIndex::end()` for example). I am not sure which is better, return an invalid edge/action/value or a none Result.
    + For avoiding tuples, cannot agree more ;P

**Comment by ZhangZhuoSJTU** [comment]
> Some functions are taking references to NodeIndex/EdgeIndex while some are not. Maybe we need to update those properly to follow a set standard.

For this, all the functions in CFGMod/SSAMod use references, while all the functions in CFG/SSA are not. I think it maybe more suitable for rust? Like what `HashSet` does, all the function which just get information are using references and all the function which will change its value will use value itself

**Comment by XVilka** [comment]
What do you think about adding attributes to the nodes? https://github.com/radare/radeco-lib/issues/55 (and corresponding API)

**Comment by ZhangZhuoSJTU** [comment]
@XVilka Agree, and I think we should add these into SSAExtra. Following is what SSAExtra should contain.

-    [x] `mark` for DCE
-    [x] `comment` for any comment on every node
-    [x] `color` for something I haven't known, actually
-    [x] `flag` for something I haven't known, neither
-    [ ] `range` for a set of value ranges
-    [ ] `type` for some type information which could be gathered from users or analysis

maybe something more is needed to be added?

**Comment by sushant94** [comment]
Adding in more to this discussion:
- I believe that for functions which may fail to return a real value, we return a `Result`, or at the very least, as `Option`. The caller can then decide what to do. Current behavior can be replicated using `result.unwrap_or(invalid_value)`, so this shouldn't be a problem.
- I think the APIs can take references as arguments and return references (`&NodeIndex`). This would prevent needless copy/clones (although this may be a small optimization as I don't expect `NodeIndex` to be a large struct). We need to standardize this, either always take/return references, or never.
- For SSAExtra, I believe we must be able to associate arbitrary information with nodes. I would suggest we maintain a `HashMap<NodeIndex, HashMap<Key, SerializedFormat>>`. Any information to be associated must be serializeble to this form. Since these are auxillary data and should/will be used only for a few passes, the overhead for serialization may be acceptable.

**Comment by XVilka** [comment]
- I agree with @sushant94 about the Option/Result type for return values. 
 - Yes, good idea about using HashMap about storing arbitrary information with nodes.

**Comment by ZhangZhuoSJTU** [comment]
+ For return values, I think every `get_xxx` function should return Option/Result type or Vec (which could be empty to state None), maybe in this way, APIs will looks uniform. And because actually, only few get_xxx functions will have an accurate return value, like `get_selects_for `.  
+ For always taking/returning references or never, I think maybe what `HashMap` has done is better. For some functions like `get_xxx`, `remove_xxx`, `replace_xxx`, which don't need own the argument,  references is used. Meanwhile for some functions like `insert_xxx`, which will get the ownership, value should be should. Emm, I mean, maybe following `HashMap` API design is more logical?
Btw, in my opinion, NodeIndex maybe just a wrapper of usize, while using reference may not have optimization?

**Comment by sushant94** [comment]
@ZhangZhuoSJTU More suggestions (I'll update here if I see any more):
- Rename start_node in CFG with entry_node. This makes more sense as entry/exit node is the more conventional terms.

**Comment by ZhangZhuoSJTU** [comment]
Update APIs, please check. And I will make a PR within 24 hours. If there are some other suggestions, we could make some changes basing on this ;P

**Comment by chinmaydd** [comment]
I think rather than `Option` we should be using `Result`. We can be more verbose about what errors we handle what we dont. But this is okay I guess.

Also what about the plan for avoiding tuples? :P We can define a struct with all fields of type `Option<MainType>` so that we can set the rest as `None` and just provide the ones we want.

Apart from that it looks good :+1:

**Comment by ZhangZhuoSJTU** [comment]
@chinmaydd  Hah, For tuples, I have written in the code, but forget the change the list ;P
And for `Option`, I think `Option` is much better, for sometimes, it's not an error, but just do not have this value.

**Comment by XVilka** [comment]
Result of an Option.

**Comment by chinmaydd** [comment]
Ok, I dont know if I am too late but discovered this yesterday: https://github.com/rust-lang/rfcs/blob/master/text/0344-conventions-galore.md#gettersetter-apis . We might have to get rid of the "get_" prefix for getter methods. :P

**Comment by ZhangZhuoSJTU** [comment]
@chinmaydd let me check, if it's ok, I could do the change.

**Comment by ZhangZhuoSJTU** [comment]
Make a reference to NodeIndex/EdgeIndex is redundant, imho. Because NodeIndex/EdgeIndex is only a simple index number, and works as a reference.
