### ISSUE TITLE
IR Opcode Extensions

### ISSUE THREAD

**Issue by sushant94** [radare/radeco-lib#87]
`rol` and `ror` opcodes in ssaconstructor are currently unimplemented. This is a good time to reconsider the opcodes we currently have radeco-ir.

Discussion:
- Do we want separate opcodes for these? or do we do this with a combination of shifts and bit masks.
- Should we replace OpWiden with separate opcodes for zero and sign extend? (Issue #78)
- Do we need operation such as Concat and Extract (corresponding to similar operations in smtlib)

**Comment by sushant94** [comment]
Related discussion:
- Should we replace OpWiden with separate opcodes for zero and sign extend? (Issue #78)
- Do we need operation such as Concat and Extract (corresponding to similar operations in smtlib)

**Comment by ZhangZhuoSJTU** [comment]
@sushant94 

+ For `rol` and `ror` opcodes, I think it may be better to separate opcodes. Because `rol` and `ror` opcodes not only read value from variables(registers), but also write value on them. Thus, these two opcodes cannot be applied on some partial registers simply. For example, we can easily apply `rol` on `eax` on 32-bit machine, but we cannot apply `rol` on `al` which is `OpAnd` from `eax`.
+ For zero and sign extend, I need to think for a while. Because if we apply `OpNarrow` on all the constants when necessary, I'm not sure whether it's necessary to replace OpWiden. Maybe there are some special cases, maybe not. 
+ For Concat and Extract, not sure actually.

**Comment by XVilka** [comment]
I think ROL and ROL like instructions are presented on many architectures, it make sense to add them.

**Comment by XVilka** [comment]
Concat and Extract can be useful on SSE/AVX/NEON-like instructions.

**Comment by sushant94** [comment]
Done in #96. Concat/Extract can be added later on when we find them necessary.
